// flow-typed signature: 21fbf921203e824baa2b5fab12fa4244
// flow-typed version: <<STUB>>/axios-mock-adapter_v1.9.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'axios-mock-adapter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'axios-mock-adapter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'axios-mock-adapter/dist/axios-mock-adapter' {
  declare module.exports: any;
}

declare module 'axios-mock-adapter/dist/axios-mock-adapter.min' {
  declare module.exports: any;
}

declare module 'axios-mock-adapter/src/handle_request' {
  declare module.exports: any;
}

declare module 'axios-mock-adapter/src/index' {
  declare module.exports: any;
}

declare module 'axios-mock-adapter/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'axios-mock-adapter/dist/axios-mock-adapter.js' {
  declare module.exports: $Exports<'axios-mock-adapter/dist/axios-mock-adapter'>;
}
declare module 'axios-mock-adapter/dist/axios-mock-adapter.min.js' {
  declare module.exports: $Exports<'axios-mock-adapter/dist/axios-mock-adapter.min'>;
}
declare module 'axios-mock-adapter/src/handle_request.js' {
  declare module.exports: $Exports<'axios-mock-adapter/src/handle_request'>;
}
declare module 'axios-mock-adapter/src/index.js' {
  declare module.exports: $Exports<'axios-mock-adapter/src/index'>;
}
declare module 'axios-mock-adapter/src/utils.js' {
  declare module.exports: $Exports<'axios-mock-adapter/src/utils'>;
}
