// flow-typed signature: 6651ec39332d000b3bdd725623017290
// flow-typed version: <<STUB>>/electron-rebuild_v1.6.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-rebuild'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-rebuild' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-rebuild/lib/src/cli' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/src/electron-locater' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/src/main' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/src/read-package-json' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/src/rebuild' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-rebuild/lib/src/cli.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/src/cli'>;
}
declare module 'electron-rebuild/lib/src/electron-locater.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/src/electron-locater'>;
}
declare module 'electron-rebuild/lib/src/main.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/src/main'>;
}
declare module 'electron-rebuild/lib/src/read-package-json.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/src/read-package-json'>;
}
declare module 'electron-rebuild/lib/src/rebuild.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/src/rebuild'>;
}
