// flow-typed signature: cd981df3bffd155d364f67e2bc4d73d2
// flow-typed version: <<STUB>>/electron-save-file_v1.0.2/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-save-file'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-save-file' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'electron-save-file/index' {
  declare module.exports: $Exports<'electron-save-file'>;
}
declare module 'electron-save-file/index.js' {
  declare module.exports: $Exports<'electron-save-file'>;
}
