// flow-typed signature: a673c3738e476492b81b125fef6bce60
// flow-typed version: <<STUB>>/elliptic_v6.4.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'elliptic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'elliptic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'elliptic/lib/elliptic' {
  declare module.exports: any;
}

declare module 'elliptic/lib/elliptic/curve/base' {
  declare module.exports: any;
}

declare module 'elliptic/lib/elliptic/curve/edwards' {
  declare module.exports: any;
}

declare module 'elliptic/lib/elliptic/curve/index' {
  declare module.exports: any;
}

declare module 'elliptic/lib/elliptic/curve/mont' {
  declare module.exports: any;
}

declare module 'elliptic/lib/elliptic/curve/short' {
  declare module.exports: any;
}

declare module 'elliptic/lib/elliptic/curves' {
  declare module.exports: any;
}

declare module 'elliptic/lib/elliptic/ec/index' {
  declare module.exports: any;
}

declare module 'elliptic/lib/elliptic/ec/key' {
  declare module.exports: any;
}

declare module 'elliptic/lib/elliptic/ec/signature' {
  declare module.exports: any;
}

declare module 'elliptic/lib/elliptic/eddsa/index' {
  declare module.exports: any;
}

declare module 'elliptic/lib/elliptic/eddsa/key' {
  declare module.exports: any;
}

declare module 'elliptic/lib/elliptic/eddsa/signature' {
  declare module.exports: any;
}

declare module 'elliptic/lib/elliptic/precomputed/secp256k1' {
  declare module.exports: any;
}

declare module 'elliptic/lib/elliptic/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'elliptic/lib/elliptic.js' {
  declare module.exports: $Exports<'elliptic/lib/elliptic'>;
}
declare module 'elliptic/lib/elliptic/curve/base.js' {
  declare module.exports: $Exports<'elliptic/lib/elliptic/curve/base'>;
}
declare module 'elliptic/lib/elliptic/curve/edwards.js' {
  declare module.exports: $Exports<'elliptic/lib/elliptic/curve/edwards'>;
}
declare module 'elliptic/lib/elliptic/curve/index.js' {
  declare module.exports: $Exports<'elliptic/lib/elliptic/curve/index'>;
}
declare module 'elliptic/lib/elliptic/curve/mont.js' {
  declare module.exports: $Exports<'elliptic/lib/elliptic/curve/mont'>;
}
declare module 'elliptic/lib/elliptic/curve/short.js' {
  declare module.exports: $Exports<'elliptic/lib/elliptic/curve/short'>;
}
declare module 'elliptic/lib/elliptic/curves.js' {
  declare module.exports: $Exports<'elliptic/lib/elliptic/curves'>;
}
declare module 'elliptic/lib/elliptic/ec/index.js' {
  declare module.exports: $Exports<'elliptic/lib/elliptic/ec/index'>;
}
declare module 'elliptic/lib/elliptic/ec/key.js' {
  declare module.exports: $Exports<'elliptic/lib/elliptic/ec/key'>;
}
declare module 'elliptic/lib/elliptic/ec/signature.js' {
  declare module.exports: $Exports<'elliptic/lib/elliptic/ec/signature'>;
}
declare module 'elliptic/lib/elliptic/eddsa/index.js' {
  declare module.exports: $Exports<'elliptic/lib/elliptic/eddsa/index'>;
}
declare module 'elliptic/lib/elliptic/eddsa/key.js' {
  declare module.exports: $Exports<'elliptic/lib/elliptic/eddsa/key'>;
}
declare module 'elliptic/lib/elliptic/eddsa/signature.js' {
  declare module.exports: $Exports<'elliptic/lib/elliptic/eddsa/signature'>;
}
declare module 'elliptic/lib/elliptic/precomputed/secp256k1.js' {
  declare module.exports: $Exports<'elliptic/lib/elliptic/precomputed/secp256k1'>;
}
declare module 'elliptic/lib/elliptic/utils.js' {
  declare module.exports: $Exports<'elliptic/lib/elliptic/utils'>;
}
