// flow-typed signature: f6768101e2c5929224f9cc6739ab5c6d
// flow-typed version: <<STUB>>/fs_v0.0.1-security/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fs' {
  declare module.exports: any;
}
