// flow-typed signature: db5806735e768121f16848d5653ff439
// flow-typed version: <<STUB>>/js-scrypt_v0.2.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-scrypt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-scrypt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-scrypt/lib/argument-scrubber' {
  declare module.exports: any;
}

declare module 'js-scrypt/lib/scrypt-async-worker' {
  declare module.exports: any;
}

declare module 'js-scrypt/lib/scrypt-async' {
  declare module.exports: any;
}

declare module 'js-scrypt/lib/scrypt-module-factory' {
  declare module.exports: any;
}

declare module 'js-scrypt/lib/scrypt-sync' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-scrypt/index' {
  declare module.exports: $Exports<'js-scrypt'>;
}
declare module 'js-scrypt/index.js' {
  declare module.exports: $Exports<'js-scrypt'>;
}
declare module 'js-scrypt/lib/argument-scrubber.js' {
  declare module.exports: $Exports<'js-scrypt/lib/argument-scrubber'>;
}
declare module 'js-scrypt/lib/scrypt-async-worker.js' {
  declare module.exports: $Exports<'js-scrypt/lib/scrypt-async-worker'>;
}
declare module 'js-scrypt/lib/scrypt-async.js' {
  declare module.exports: $Exports<'js-scrypt/lib/scrypt-async'>;
}
declare module 'js-scrypt/lib/scrypt-module-factory.js' {
  declare module.exports: $Exports<'js-scrypt/lib/scrypt-module-factory'>;
}
declare module 'js-scrypt/lib/scrypt-sync.js' {
  declare module.exports: $Exports<'js-scrypt/lib/scrypt-sync'>;
}
