// flow-typed signature: bfeaced29c5ad71894cfa7a118bb2e3d
// flow-typed version: <<STUB>>/neon-js_vgit+https://github.com/dvdschwrtz/neon-js.git#6d4a065e277ccae524d45fd9a5f4662d05fbbfca/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'neon-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'neon-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'neon-js/build/html/_static/doctools' {
  declare module.exports: any;
}

declare module 'neon-js/build/html/_static/jquery-3.1.0' {
  declare module.exports: any;
}

declare module 'neon-js/build/html/_static/jquery' {
  declare module.exports: any;
}

declare module 'neon-js/build/html/_static/js/modernizr.min' {
  declare module.exports: any;
}

declare module 'neon-js/build/html/_static/js/theme' {
  declare module.exports: any;
}

declare module 'neon-js/build/html/_static/searchtools' {
  declare module.exports: any;
}

declare module 'neon-js/build/html/_static/underscore-1.3.1' {
  declare module.exports: any;
}

declare module 'neon-js/build/html/_static/underscore' {
  declare module.exports: any;
}

declare module 'neon-js/build/html/_static/websupport' {
  declare module.exports: any;
}

declare module 'neon-js/build/html/searchindex' {
  declare module.exports: any;
}

declare module 'neon-js/lib/index' {
  declare module.exports: any;
}

declare module 'neon-js/src/api' {
  declare module.exports: any;
}

declare module 'neon-js/src/index' {
  declare module.exports: any;
}

declare module 'neon-js/src/nep2' {
  declare module.exports: any;
}

declare module 'neon-js/src/nep5' {
  declare module.exports: any;
}

declare module 'neon-js/src/sc/opCode' {
  declare module.exports: any;
}

declare module 'neon-js/src/sc/scriptBuilder' {
  declare module.exports: any;
}

declare module 'neon-js/src/transactions' {
  declare module.exports: any;
}

declare module 'neon-js/src/transactions/components' {
  declare module.exports: any;
}

declare module 'neon-js/src/transactions/create' {
  declare module.exports: any;
}

declare module 'neon-js/src/transactions/exclusive' {
  declare module.exports: any;
}

declare module 'neon-js/src/transactions/index' {
  declare module.exports: any;
}

declare module 'neon-js/src/utils' {
  declare module.exports: any;
}

declare module 'neon-js/src/wallet' {
  declare module.exports: any;
}

declare module 'neon-js/tests/common' {
  declare module.exports: any;
}

declare module 'neon-js/tests/index' {
  declare module.exports: any;
}

declare module 'neon-js/tests/nep5' {
  declare module.exports: any;
}

declare module 'neon-js/tests/rpx' {
  declare module.exports: any;
}

declare module 'neon-js/tests/sc/scriptBuilder' {
  declare module.exports: any;
}

declare module 'neon-js/tests/transactions/components' {
  declare module.exports: any;
}

declare module 'neon-js/tests/transactions/create' {
  declare module.exports: any;
}

declare module 'neon-js/tests/transactions/index' {
  declare module.exports: any;
}

declare module 'neon-js/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'neon-js/build/html/_static/doctools.js' {
  declare module.exports: $Exports<'neon-js/build/html/_static/doctools'>;
}
declare module 'neon-js/build/html/_static/jquery-3.1.0.js' {
  declare module.exports: $Exports<'neon-js/build/html/_static/jquery-3.1.0'>;
}
declare module 'neon-js/build/html/_static/jquery.js' {
  declare module.exports: $Exports<'neon-js/build/html/_static/jquery'>;
}
declare module 'neon-js/build/html/_static/js/modernizr.min.js' {
  declare module.exports: $Exports<'neon-js/build/html/_static/js/modernizr.min'>;
}
declare module 'neon-js/build/html/_static/js/theme.js' {
  declare module.exports: $Exports<'neon-js/build/html/_static/js/theme'>;
}
declare module 'neon-js/build/html/_static/searchtools.js' {
  declare module.exports: $Exports<'neon-js/build/html/_static/searchtools'>;
}
declare module 'neon-js/build/html/_static/underscore-1.3.1.js' {
  declare module.exports: $Exports<'neon-js/build/html/_static/underscore-1.3.1'>;
}
declare module 'neon-js/build/html/_static/underscore.js' {
  declare module.exports: $Exports<'neon-js/build/html/_static/underscore'>;
}
declare module 'neon-js/build/html/_static/websupport.js' {
  declare module.exports: $Exports<'neon-js/build/html/_static/websupport'>;
}
declare module 'neon-js/build/html/searchindex.js' {
  declare module.exports: $Exports<'neon-js/build/html/searchindex'>;
}
declare module 'neon-js/lib/index.js' {
  declare module.exports: $Exports<'neon-js/lib/index'>;
}
declare module 'neon-js/src/api.js' {
  declare module.exports: $Exports<'neon-js/src/api'>;
}
declare module 'neon-js/src/index.js' {
  declare module.exports: $Exports<'neon-js/src/index'>;
}
declare module 'neon-js/src/nep2.js' {
  declare module.exports: $Exports<'neon-js/src/nep2'>;
}
declare module 'neon-js/src/nep5.js' {
  declare module.exports: $Exports<'neon-js/src/nep5'>;
}
declare module 'neon-js/src/sc/opCode.js' {
  declare module.exports: $Exports<'neon-js/src/sc/opCode'>;
}
declare module 'neon-js/src/sc/scriptBuilder.js' {
  declare module.exports: $Exports<'neon-js/src/sc/scriptBuilder'>;
}
declare module 'neon-js/src/transactions.js' {
  declare module.exports: $Exports<'neon-js/src/transactions'>;
}
declare module 'neon-js/src/transactions/components.js' {
  declare module.exports: $Exports<'neon-js/src/transactions/components'>;
}
declare module 'neon-js/src/transactions/create.js' {
  declare module.exports: $Exports<'neon-js/src/transactions/create'>;
}
declare module 'neon-js/src/transactions/exclusive.js' {
  declare module.exports: $Exports<'neon-js/src/transactions/exclusive'>;
}
declare module 'neon-js/src/transactions/index.js' {
  declare module.exports: $Exports<'neon-js/src/transactions/index'>;
}
declare module 'neon-js/src/utils.js' {
  declare module.exports: $Exports<'neon-js/src/utils'>;
}
declare module 'neon-js/src/wallet.js' {
  declare module.exports: $Exports<'neon-js/src/wallet'>;
}
declare module 'neon-js/tests/common.js' {
  declare module.exports: $Exports<'neon-js/tests/common'>;
}
declare module 'neon-js/tests/index.js' {
  declare module.exports: $Exports<'neon-js/tests/index'>;
}
declare module 'neon-js/tests/nep5.js' {
  declare module.exports: $Exports<'neon-js/tests/nep5'>;
}
declare module 'neon-js/tests/rpx.js' {
  declare module.exports: $Exports<'neon-js/tests/rpx'>;
}
declare module 'neon-js/tests/sc/scriptBuilder.js' {
  declare module.exports: $Exports<'neon-js/tests/sc/scriptBuilder'>;
}
declare module 'neon-js/tests/transactions/components.js' {
  declare module.exports: $Exports<'neon-js/tests/transactions/components'>;
}
declare module 'neon-js/tests/transactions/create.js' {
  declare module.exports: $Exports<'neon-js/tests/transactions/create'>;
}
declare module 'neon-js/tests/transactions/index.js' {
  declare module.exports: $Exports<'neon-js/tests/transactions/index'>;
}
declare module 'neon-js/webpack.config.js' {
  declare module.exports: $Exports<'neon-js/webpack.config'>;
}
