// flow-typed signature: 37118333ced4804a37243a8046a0bfd3
// flow-typed version: <<STUB>>/qrcode_v0.9.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'qrcode'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'qrcode' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'qrcode/build/qrcode' {
  declare module.exports: any;
}

declare module 'qrcode/build/qrcode.min' {
  declare module.exports: any;
}

declare module 'qrcode/build/qrcode.tosjis' {
  declare module.exports: any;
}

declare module 'qrcode/build/qrcode.tosjis.min' {
  declare module.exports: any;
}

declare module 'qrcode/helper/to-sjis' {
  declare module.exports: any;
}

declare module 'qrcode/lib/browser' {
  declare module.exports: any;
}

declare module 'qrcode/lib/core/alignment-pattern' {
  declare module.exports: any;
}

declare module 'qrcode/lib/core/alphanumeric-data' {
  declare module.exports: any;
}

declare module 'qrcode/lib/core/bit-buffer' {
  declare module.exports: any;
}

declare module 'qrcode/lib/core/bit-matrix' {
  declare module.exports: any;
}

declare module 'qrcode/lib/core/byte-data' {
  declare module.exports: any;
}

declare module 'qrcode/lib/core/error-correction-code' {
  declare module.exports: any;
}

declare module 'qrcode/lib/core/error-correction-level' {
  declare module.exports: any;
}

declare module 'qrcode/lib/core/finder-pattern' {
  declare module.exports: any;
}

declare module 'qrcode/lib/core/format-info' {
  declare module.exports: any;
}

declare module 'qrcode/lib/core/galois-field' {
  declare module.exports: any;
}

declare module 'qrcode/lib/core/kanji-data' {
  declare module.exports: any;
}

declare module 'qrcode/lib/core/mask-pattern' {
  declare module.exports: any;
}

declare module 'qrcode/lib/core/mode' {
  declare module.exports: any;
}

declare module 'qrcode/lib/core/numeric-data' {
  declare module.exports: any;
}

declare module 'qrcode/lib/core/polynomial' {
  declare module.exports: any;
}

declare module 'qrcode/lib/core/qrcode' {
  declare module.exports: any;
}

declare module 'qrcode/lib/core/reed-solomon-encoder' {
  declare module.exports: any;
}

declare module 'qrcode/lib/core/regex' {
  declare module.exports: any;
}

declare module 'qrcode/lib/core/segments' {
  declare module.exports: any;
}

declare module 'qrcode/lib/core/utils' {
  declare module.exports: any;
}

declare module 'qrcode/lib/core/version' {
  declare module.exports: any;
}

declare module 'qrcode/lib/index' {
  declare module.exports: any;
}

declare module 'qrcode/lib/renderer/canvas' {
  declare module.exports: any;
}

declare module 'qrcode/lib/renderer/png' {
  declare module.exports: any;
}

declare module 'qrcode/lib/renderer/svg-render' {
  declare module.exports: any;
}

declare module 'qrcode/lib/renderer/svg' {
  declare module.exports: any;
}

declare module 'qrcode/lib/renderer/terminal' {
  declare module.exports: any;
}

declare module 'qrcode/lib/renderer/utf8' {
  declare module.exports: any;
}

declare module 'qrcode/lib/renderer/utils' {
  declare module.exports: any;
}

declare module 'qrcode/lib/server' {
  declare module.exports: any;
}

declare module 'qrcode/lib/utils/buffer' {
  declare module.exports: any;
}

declare module 'qrcode/lib/utils/typedarray-buffer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'qrcode/build/qrcode.js' {
  declare module.exports: $Exports<'qrcode/build/qrcode'>;
}
declare module 'qrcode/build/qrcode.min.js' {
  declare module.exports: $Exports<'qrcode/build/qrcode.min'>;
}
declare module 'qrcode/build/qrcode.tosjis.js' {
  declare module.exports: $Exports<'qrcode/build/qrcode.tosjis'>;
}
declare module 'qrcode/build/qrcode.tosjis.min.js' {
  declare module.exports: $Exports<'qrcode/build/qrcode.tosjis.min'>;
}
declare module 'qrcode/helper/to-sjis.js' {
  declare module.exports: $Exports<'qrcode/helper/to-sjis'>;
}
declare module 'qrcode/lib/browser.js' {
  declare module.exports: $Exports<'qrcode/lib/browser'>;
}
declare module 'qrcode/lib/core/alignment-pattern.js' {
  declare module.exports: $Exports<'qrcode/lib/core/alignment-pattern'>;
}
declare module 'qrcode/lib/core/alphanumeric-data.js' {
  declare module.exports: $Exports<'qrcode/lib/core/alphanumeric-data'>;
}
declare module 'qrcode/lib/core/bit-buffer.js' {
  declare module.exports: $Exports<'qrcode/lib/core/bit-buffer'>;
}
declare module 'qrcode/lib/core/bit-matrix.js' {
  declare module.exports: $Exports<'qrcode/lib/core/bit-matrix'>;
}
declare module 'qrcode/lib/core/byte-data.js' {
  declare module.exports: $Exports<'qrcode/lib/core/byte-data'>;
}
declare module 'qrcode/lib/core/error-correction-code.js' {
  declare module.exports: $Exports<'qrcode/lib/core/error-correction-code'>;
}
declare module 'qrcode/lib/core/error-correction-level.js' {
  declare module.exports: $Exports<'qrcode/lib/core/error-correction-level'>;
}
declare module 'qrcode/lib/core/finder-pattern.js' {
  declare module.exports: $Exports<'qrcode/lib/core/finder-pattern'>;
}
declare module 'qrcode/lib/core/format-info.js' {
  declare module.exports: $Exports<'qrcode/lib/core/format-info'>;
}
declare module 'qrcode/lib/core/galois-field.js' {
  declare module.exports: $Exports<'qrcode/lib/core/galois-field'>;
}
declare module 'qrcode/lib/core/kanji-data.js' {
  declare module.exports: $Exports<'qrcode/lib/core/kanji-data'>;
}
declare module 'qrcode/lib/core/mask-pattern.js' {
  declare module.exports: $Exports<'qrcode/lib/core/mask-pattern'>;
}
declare module 'qrcode/lib/core/mode.js' {
  declare module.exports: $Exports<'qrcode/lib/core/mode'>;
}
declare module 'qrcode/lib/core/numeric-data.js' {
  declare module.exports: $Exports<'qrcode/lib/core/numeric-data'>;
}
declare module 'qrcode/lib/core/polynomial.js' {
  declare module.exports: $Exports<'qrcode/lib/core/polynomial'>;
}
declare module 'qrcode/lib/core/qrcode.js' {
  declare module.exports: $Exports<'qrcode/lib/core/qrcode'>;
}
declare module 'qrcode/lib/core/reed-solomon-encoder.js' {
  declare module.exports: $Exports<'qrcode/lib/core/reed-solomon-encoder'>;
}
declare module 'qrcode/lib/core/regex.js' {
  declare module.exports: $Exports<'qrcode/lib/core/regex'>;
}
declare module 'qrcode/lib/core/segments.js' {
  declare module.exports: $Exports<'qrcode/lib/core/segments'>;
}
declare module 'qrcode/lib/core/utils.js' {
  declare module.exports: $Exports<'qrcode/lib/core/utils'>;
}
declare module 'qrcode/lib/core/version.js' {
  declare module.exports: $Exports<'qrcode/lib/core/version'>;
}
declare module 'qrcode/lib/index.js' {
  declare module.exports: $Exports<'qrcode/lib/index'>;
}
declare module 'qrcode/lib/renderer/canvas.js' {
  declare module.exports: $Exports<'qrcode/lib/renderer/canvas'>;
}
declare module 'qrcode/lib/renderer/png.js' {
  declare module.exports: $Exports<'qrcode/lib/renderer/png'>;
}
declare module 'qrcode/lib/renderer/svg-render.js' {
  declare module.exports: $Exports<'qrcode/lib/renderer/svg-render'>;
}
declare module 'qrcode/lib/renderer/svg.js' {
  declare module.exports: $Exports<'qrcode/lib/renderer/svg'>;
}
declare module 'qrcode/lib/renderer/terminal.js' {
  declare module.exports: $Exports<'qrcode/lib/renderer/terminal'>;
}
declare module 'qrcode/lib/renderer/utf8.js' {
  declare module.exports: $Exports<'qrcode/lib/renderer/utf8'>;
}
declare module 'qrcode/lib/renderer/utils.js' {
  declare module.exports: $Exports<'qrcode/lib/renderer/utils'>;
}
declare module 'qrcode/lib/server.js' {
  declare module.exports: $Exports<'qrcode/lib/server'>;
}
declare module 'qrcode/lib/utils/buffer.js' {
  declare module.exports: $Exports<'qrcode/lib/utils/buffer'>;
}
declare module 'qrcode/lib/utils/typedarray-buffer.js' {
  declare module.exports: $Exports<'qrcode/lib/utils/typedarray-buffer'>;
}
