// flow-typed signature: 3b24891d678da15fb096c08d951c7ebf
// flow-typed version: <<STUB>>/react-notification-system_v0.2.16/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-notification-system'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-notification-system' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-notification-system/dist/constants' {
  declare module.exports: any;
}

declare module 'react-notification-system/dist/helpers' {
  declare module.exports: any;
}

declare module 'react-notification-system/dist/NotificationContainer' {
  declare module.exports: any;
}

declare module 'react-notification-system/dist/NotificationItem' {
  declare module.exports: any;
}

declare module 'react-notification-system/dist/NotificationSystem' {
  declare module.exports: any;
}

declare module 'react-notification-system/dist/react-notification-system' {
  declare module.exports: any;
}

declare module 'react-notification-system/dist/react-notification-system.min' {
  declare module.exports: any;
}

declare module 'react-notification-system/dist/styles' {
  declare module.exports: any;
}

declare module 'react-notification-system/karma.conf' {
  declare module.exports: any;
}

declare module 'react-notification-system/src/constants' {
  declare module.exports: any;
}

declare module 'react-notification-system/src/helpers' {
  declare module.exports: any;
}

declare module 'react-notification-system/src/NotificationContainer' {
  declare module.exports: any;
}

declare module 'react-notification-system/src/NotificationItem' {
  declare module.exports: any;
}

declare module 'react-notification-system/src/NotificationSystem' {
  declare module.exports: any;
}

declare module 'react-notification-system/src/styles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-notification-system/dist/constants.js' {
  declare module.exports: $Exports<'react-notification-system/dist/constants'>;
}
declare module 'react-notification-system/dist/helpers.js' {
  declare module.exports: $Exports<'react-notification-system/dist/helpers'>;
}
declare module 'react-notification-system/dist/NotificationContainer.js' {
  declare module.exports: $Exports<'react-notification-system/dist/NotificationContainer'>;
}
declare module 'react-notification-system/dist/NotificationItem.js' {
  declare module.exports: $Exports<'react-notification-system/dist/NotificationItem'>;
}
declare module 'react-notification-system/dist/NotificationSystem.js' {
  declare module.exports: $Exports<'react-notification-system/dist/NotificationSystem'>;
}
declare module 'react-notification-system/dist/react-notification-system.js' {
  declare module.exports: $Exports<'react-notification-system/dist/react-notification-system'>;
}
declare module 'react-notification-system/dist/react-notification-system.min.js' {
  declare module.exports: $Exports<'react-notification-system/dist/react-notification-system.min'>;
}
declare module 'react-notification-system/dist/styles.js' {
  declare module.exports: $Exports<'react-notification-system/dist/styles'>;
}
declare module 'react-notification-system/karma.conf.js' {
  declare module.exports: $Exports<'react-notification-system/karma.conf'>;
}
declare module 'react-notification-system/src/constants.js' {
  declare module.exports: $Exports<'react-notification-system/src/constants'>;
}
declare module 'react-notification-system/src/helpers.js' {
  declare module.exports: $Exports<'react-notification-system/src/helpers'>;
}
declare module 'react-notification-system/src/NotificationContainer.jsx' {
  declare module.exports: $Exports<'react-notification-system/src/NotificationContainer'>;
}
declare module 'react-notification-system/src/NotificationItem.jsx' {
  declare module.exports: $Exports<'react-notification-system/src/NotificationItem'>;
}
declare module 'react-notification-system/src/NotificationSystem.jsx' {
  declare module.exports: $Exports<'react-notification-system/src/NotificationSystem'>;
}
declare module 'react-notification-system/src/styles.js' {
  declare module.exports: $Exports<'react-notification-system/src/styles'>;
}
