// flow-typed signature: 8971927d8b65ffa769580a81b8e9ad2b
// flow-typed version: <<STUB>>/react-data-grid_v2.0.73/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-data-grid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-data-grid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-data-grid/dist/react-data-grid' {
  declare module.exports: any;
}

declare module 'react-data-grid/dist/react-data-grid.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-data-grid/dist/react-data-grid.js' {
  declare module.exports: $Exports<'react-data-grid/dist/react-data-grid'>;
}
declare module 'react-data-grid/dist/react-data-grid.min.js' {
  declare module.exports: $Exports<'react-data-grid/dist/react-data-grid.min'>;
}
declare module 'react-data-grid/index' {
  declare module.exports: $Exports<'react-data-grid'>;
}
declare module 'react-data-grid/index.js' {
  declare module.exports: $Exports<'react-data-grid'>;
}
