// flow-typed signature: 6d9ae471ee7717a6e40eecb23c7249da
// flow-typed version: <<STUB>>/secure-random_v1.1.1/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'secure-random'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'secure-random' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'secure-random/lib/secure-random' {
  declare module.exports: any;
}

// Filename aliases
declare module 'secure-random/lib/secure-random.js' {
  declare module.exports: $Exports<'secure-random/lib/secure-random'>;
}
