// flow-typed signature: f2527ad951f348de58dbc28b74983c12
// flow-typed version: <<STUB>>/wif_v2.0.6/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wif'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wif' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wif/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wif/index' {
  declare module.exports: $Exports<'wif'>;
}
declare module 'wif/index.js' {
  declare module.exports: $Exports<'wif'>;
}
declare module 'wif/test/index.js' {
  declare module.exports: $Exports<'wif/test/index'>;
}
